Get workflows perf
dvargas92495/roamjs-smartblocks pull request #76
Opened 2023-04-09 18:27 UTC by dvargas92495

2023-04-09 18:28 UTC, dvargas92495 commented on src/core.ts
> +      `[:find (pull ?r [:block/uid :block/string]) :where [?sb :node/title "SmartBlock"] [?old :node/title "42SmartBlock"] (or [?r :block/refs ?old] [?r :block/refs ?sb])]`
There are some low hanging fruit plaguing sb/qb users that we can start resolving. This involves two:
- always use `data.fast.q` over `q`.
- reorder clauses to prioritize ones with high specificity first

2023-04-09 20:47 UTC, mdroidian requested changes
Interesting, this seems to not recognize any of my Smartblocks:

![image](https://user-images.githubusercontent.com/3792666/230795787-7a72f2db-d258-4a63-a18b-64298bbee835.png)

2023-04-09 22:41 UTC, dvargas92495 commented on src/core.ts
> +)]`
the previous version broke when the user didn't have `42SmartBlock` in their graph -.-

I thought about getting rid of it, but this works too so kept it for any legacy users out there

2023-04-10 16:43 UTC, mdroidian approved these changes

2023-04-10 16:43 UTC, merged